### PR TITLE
fix(NavigationMenu): change a tag styles and header visibility logic

### LINKED ISSUE #16: [Bug]: NavigationMenu style bug
### Component

NavigationMenu

### Describe the bug

If NavigationMenu data has title `<a>title</a>` and icon, they are getting on each other.

### To Reproduce

1. Into NavigationMenu data give as title `<a href="#">test</a>` and some icon.
2. Open NavigationMenu

### Expected behavior

The Link must look like other navigation list items.

### Screenshots

Screenshot 2023-11-21 at 14 40 54

### Package version

v2.11.0

### Desktop

. OS: macOS Sonoma 14.1.1
. Browser & version: Google Chrome 119.0.6045.159

### Smartphone

_No response_

### Exception or Error

_No response_

### Additional context

data for testing ->

```
const data = [
    {
        id: '1',
        title: 'Section 1',
        icon: 'bc-icon-send-pop-up-block'

    },
    {
        title: <a href="#">test</a>,
        id: 111,
        icon: 'bc-icon-time-filter',
    }
];
```

### PR DESCRIPTION
**Pull request by GaroGabrielyan**

### CODE REVIEW

File: src/lib/molecules/NavigationMenu/Content.js [hunk 1]
```diff
@@ -14,7 +14,10 @@ function NavigationMenuContent({ depth, path, options, onChange, splitedValue })
     const optionId = useMemo(() => splitedValue?.[depth], [depth, splitedValue]);
 
     const isActiveItem = useMemo(() => activeItem?.id && optionId === activeItem.id, [activeItem, optionId]);
-    const mobileOptions = useMemo(() => (options ? navigationOptionsToMenuMenu(options) : undefined), [options]);
+    const mobileOptions = useMemo(
+        () => (options ? navigationOptionsToMenuMenu(options, optionId) : undefined),
```
Comment (hamikhambardzumyan) [inline src/lib/molecules/NavigationMenu/Content.js:18]: Please rename the function `navigationOptionsToMenuMenu` to `navigationOptionsToMenu`.

File: src/lib/molecules/NavigationMenu/index.js [hunk 2]
```diff
@@ -36,11 +37,14 @@ function NavigationMenu({ data, value, onChange, disabled }) {
             children={
                 <button className="bc-navigation-menu" disabled={disabled}>
                     <div className="bc-navigation-menu_head">
-                        {title.map((item, index) => (
-                            <span key={index} className="bc-navigation-menu_layer">
-                                {item}
-                            </span>
-                        ))}
+                        {title.map((item, index, arr) => (
```
Comment (hamikhambardzumyan) [inline src/lib/molecules/NavigationMenu/index.js:40]: Why do you take here `arr` argument? It's not used in the scope of the `map` function.

**Review by hamikhambardzumyan — CHANGES_REQUESTED** [review]

**Review by hamikhambardzumyan — APPROVED** [review]

**Review by AregSoft — APPROVED** [review]
